# Generated by Django 2.0 on 2018-01-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='Source URL')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Dashboard Group')),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokeh_server.Group'),
        ),
    ]
